services:
  - type: web
    name: community-data-storage-hub-api
    env: python
    runtime: python
    plan: free
    buildCommand: chmod +x build.sh start.sh deploy.py && ./build.sh
    startCommand: ./start.sh
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: community-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: community-db
    plan: free
